CREATE TABLE Customer(
Customer_id Integer PRIMARY KEY NOT NULL,
cname CHARACTER VARYING NOT NULL,
Email_id CHARACTER VARYING(50) NOT NULL,
Address CHARACTER VARYING(50) NOT NULL,
SSN Integer NOT NULL,
Phone_no Integer NOT NULL)

CREATE TABLE Acount_Details(
Account_no INTEGER PRIMARY KEY NOT NULL,
Customer_id INTEGER NOT NULL,
Account_types CHARACTER VARYING(10) NOT NULL,
Branch_name CHARACTER VARYING(10) NOT NULL,
FOREIGN KEY(Customer_id) REFERENCES Customer(Customer_id))

CREATE TABLE Transactions(
Transaction_id INTEGER PRIMARY KEY NOT NULL,
Account_no INTEGER NOT NULL,
Time_stamp TIMESTAMP(10) NOT NULL
Amount INTEGER NOT NULL,
SSN INTEGER NOT NULL,
Phone_no INTEGER NOT NULL,
FOREIGN KEY(Account_no) REFERENCES Loan(Account_no))

CREATE TABLE Loan(
Loan_id INTEGER PRIMARY KEY NOT NULL,
Account_no INTEGER NOT NULL,
Requested_amount INTEGER NOT NULL,
Disbursed_amount INTEGER NOT NULL,
Collateral CHARACTER VARYING(20) NOT NULL,
Collateral_value CHARACTER VARYING(20) NOT NULL,
Sanctioning_branch CHARACTER VARYING(20) NOT NULL,
Purpose_of_loan CHARACTER VARYING(10) NOT NULL,
Branch_id INTEGER NOT NULL,
FOREIGN KEY(Branch_id) REFERENCES Branch_Details(Branch_id))

CREATE TABLE Branch_Details(
Branch_id INTEGER PRIMARY KEY NOT NULL,
IFSC_code CHARACTER VARYING(20) NOT NULL,
Pincode INTEGER NOT NULL,
Branch_manager CHARACTER VARYING(10) NOT NULL,
No_of_employees INTEGER NOT NULL)

CREATE TABLE Employee(
Emp_id INTEGER PRIMARY KEY NOT NULL,
ename CHARACTER VARYING(2) NOT NULL,
Email_id CHARACTER VARYING(20) NOT NULL,
Phone_no CHARACTER VARYING(50) NOT NULL,
SSN INTEGER NOT NULL,
Phone_no INTEGER NOT NULL,
Branch_id INTEGER NOT NULL,
FOREIGN KEY(Email_id) REFERENCES User_Login(Email_id),
FOREIGN KEY(Email_id) REFERENCES Employee_Login(Email_id))

CREATE TABLE User_Login(
User_id CHARACTER VARYING(20) PRIMARY KEY NOT NULL,
Password CHARACTER VARYING(10) NOT NULL,
Account_no INTEGER NOT NULL)

CREATE TABLE Employee_Login(
Emp_id CHARACTER VARYING(20) PRIMARY KEY NOT NULL,
Password CHARACTER VARYING(10) NOT NULL,
Account_no INTEGER NOT NULL)